### ISSUE TITLE
Practica01_PrototipoInterfaz_JudithReynaCruzSantiago_MariaJoseLopezLeyva_LitzyLopezLopez_4US

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/practicaprototipos-equipo-topicos-avanzados#2]
[Practica01_PrototipoInterfaz_JudithReynaCruzSantiago_MariaJoseLopezLeyva_LitzyLopezLopez_4US.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipo-topicos-avanzados/files/8057827/Practica01_PrototipoInterfaz_JudithReynaCruzSantiago_MariaJoseLopezLeyva_LitzyLopezLopez_4US.pdf)

LINK DEL PROTOTIPO

https://www.figma.com/file/QiCfTdolxWmnLoq0SFkdRb/Creative-Mind-Prototipo?node-id=0%3A1

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by SANDRAVELASCO** [comment]
Calificación: 20
